services:
  dklib:
    image: deankh/perception:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    container_name: dklib
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./cyclonedds.xml:/cyclonedds.xml
      - ./src:/home/developer/workspace/src
      - ./bash_history:/home/developer/.bash_history
      - ./tmux.conf:/home/developer/.tmux.conf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    user: developer
